
DROP TABLE IF EXISTS folders;

CREATE TABLE folders(
    folder_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name VARCHAR(25) NOT NULL
);

DROP TABLE IF EXISTS notes;

CREATE TABLE notes(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL, 
    note_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    reference_folder_id INT REFERENCES folders(folder_id),
    content VARCHAR(300) NOT NULL
);